### ISSUE TITLE
Users and Passwords

### ISSUE THREAD

**Issue by fredwilliamtjr** [bilak/spring-boot-security-jsf#1]
Lukáš Vasek, all right? I do not know if it's here that I ask. sorry if I'm wrong.

I am trying to use your project to study.

I saw that was created in one bank User: superuser@github.com with password: be357257807025376744e88cb47402a2285873988ca3781bc95b6fb9c01c3fe1c5414f2bb0eaeea5

More I can not log in to this User and password.

can you help me?

Note: Sorry for the English, I am Brazilian and I am using Google Translate.

**Comment by bilak** [comment]
@fredwilliamtjr I don't remember what was the password but I bet it was **password**.
Newertheles you can encode your own as you can see [here](https://github.com/bilak/spring-boot-security-jsf/blob/master/src/main/java/com/github/bilak/apptemplate/spring/confg/WebSecurityConfig.java#L34-L36) I'm using the encoder. So try something like:

```
PasswordEncoder encoder = StandardPasswordEncoder("supersecret");
System.out.println(encoder.encode("yourpasswordhere"));
```

and then add that passwords to [this file](https://github.com/bilak/spring-boot-security-jsf/blob/master/src/main/resources/import_data.sql)

**Comment by fredwilliamtjr** [comment]
It worked, thank you, if possible change your data.sql import for suggested below, just seeing that there is an error the field is_subscribed this null.

insert into users(id, email, first_name, last_name, password, is_enabled, is_locked, role_name, is_subscribed) values('1','user@github.com', 'user', 'github', '0c91031f2c22237229398b645b4d075264ec423b0ec86b1dbaa7b83fc2ce3f060b5cb2983defe411', true, false, 'ROLE_USER',true);
insert into users(id, email, first_name, last_name, password, is_enabled, is_locked, role_name, is_subscribed) values('2','admin@github.com', 'admin', 'github','0c91031f2c22237229398b645b4d075264ec423b0ec86b1dbaa7b83fc2ce3f060b5cb2983defe411', true, false, 'ROLE_ADMIN',true);
insert into users(id, email, first_name, last_name, password, is_enabled, is_locked, role_name, is_subscribed) values('3','superuser@github.com', 'superuser', 'github','0c91031f2c22237229398b645b4d075264ec423b0ec86b1dbaa7b83fc2ce3f060b5cb2983defe411', true, false, 'ROLE_SUPERUSER',true);

-- encrypted password = 1234567890
`
